%% Equations for Pu valve OPEN

clear

syms Q_p_vlv Q_PS Q_PA ... 
    P_RV P_PS P_PA P_PV ... 
    R_p_vlv R_PS R_PA R_tPA ...
    V_PS V_PA ...
    C_PS C_PA

eqns = [ Q_p_vlv == (P_RV - P_PS)/R_p_vlv, ...
    Q_PS == (P_PS - P_PA) / R_PS, ...
    Q_PA == (P_PA - P_PV)/ R_PA, ...
    P_PS == V_PS/C_PS, ...
    P_PA == (Q_PS - Q_PA)*R_tPA + V_PA/C_PA];

S = solve(eqns,[Q_p_vlv Q_PS Q_PA P_PS P_PA]);

simplify(S.Q_p_vlv)
simplify(S.Q_PS)
simplify(S.Q_PA)
simplify(S.P_PS)
simplify(S.P_PA)

%% Equations for Pu valve CLOSED

clear

syms Q_p_vlv Q_PS Q_PA ... 
    P_RV P_PS P_PA P_PV ... 
    R_p_vlv R_PS R_PA R_tPA ...
    V_PS V_PA ...
    C_PS C_PA

eqns = [ Q_PS == (P_PS - P_PA) / R_PS, ...
    Q_PA == (P_PA - P_PV)/ R_PA, ...
    P_PS == V_PS/C_PS, ...
    P_PA == (Q_PS - Q_PA)*R_tPA + V_PA/C_PA];

S = solve(eqns,[Q_PS Q_PA P_PS P_PA]);

simplify(S.Q_PS)
simplify(S.Q_PA)
simplify(S.P_PS)
simplify(S.P_PA)