
%% Equations for Ao valve OPEN

clear

syms Q_a_vlv Q_AO Q_SA ... 
    P_LV P_AO P_SA P_SV ... 
    R_a_vlv R_AO R_SA R_tSA ... 
    V_AO V_SA ...
    C_AO C_SA 

eqns = [ Q_a_vlv == (P_LV - P_AO) / R_a_vlv, ...
    Q_AO == (P_AO - P_SA) / R_AO, ... 
    Q_SA == (P_SA - P_SV) / R_SA, ... 
    P_AO == V_AO/C_AO, ... 
    P_SA == (Q_AO - Q_SA)*R_tSA + V_SA/C_SA];

S = solve(eqns,[Q_a_vlv Q_AO Q_SA P_AO P_SA]);

simplify(S.Q_a_vlv)
simplify(S.Q_AO)
simplify(S.Q_SA)
simplify(S.P_AO)
simplify(S.P_SA)

%% Equations for Ao valve CLOSED

clear

syms Q_a_vlv Q_AO Q_SA ... 
    P_LV P_AO P_SA P_SV ... 
    R_a_vlv R_AO R_SA R_tSA ... 
    V_AO V_SA ...
    C_AO C_SA 

eqns = [ Q_AO == (P_AO - P_SA) / R_AO, ... 
    Q_SA == (P_SA - P_SV) / R_SA, ... 
    P_AO == V_AO/C_AO, ... 
    P_SA == (Q_AO - Q_SA)*R_tSA + V_SA/C_SA];
S = solve(eqns,[Q_AO Q_SA P_AO P_SA ]);

simplify(S.Q_AO)
simplify(S.Q_SA)
simplify(S.P_AO)
simplify(S.P_SA)
